apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: ecommerce  # Unified label for service selection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce  # Matches service selector
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: backend
        image: us.icr.io/ecommerce-app/backend-app:1.0
        ports:
        - containerPort: 5000
