version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./public
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
 
