name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to IBM Cloud
        run: |
          ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}"
          ibmcloud cr login

      - name: Build Docker Images
        run: |
          docker build -t us.icr.io/ecommerce-app/frontend-app:1.0 ./frontend
          docker build -t us.icr.io/ecommerce-app/backend-app:1.0 ./backend

      - name: Push Docker Images to IBM Cloud
        run: |
          docker push us.icr.io/ecommerce-app/frontend-app:1.0
          docker push us.icr.io/ecommerce-app/backend-app:1.0

      - name: Deploy to IBM Code Engine
        run: |
          ibmcloud ce project create --name my-ecommerce-app-project || true
          ibmcloud ce app create --name frontend-app --image us.icr.io/ecommerce-app/frontend-app:1.0 --port 3000 --cpu 0.5 --memory 512Mi
          ibmcloud ce app create --name backend-app --image us.icr.io/ecommerce-app/backend-app:1.0 --port 5000 --cpu 0.5 --memory 512Mi
